pipeline {
    agent {
    node{
	 label 'docker'
	}
    }
    environment {
    dockerhub=credentials('dockerhub')
    }
    stages{
        stage('Docker Build') {
            steps {
                sh 'cd webapp && docker build -t harsha124/frontend .'
             }
          }
        stage('Docker Login') {
            steps {
                sh 'echo $dockerhub_PSW | docker login -u $dockerhub_USR --password-stdin'
            }
          }
        stage('Docker Push') {
            steps {
                sh 'docker push harsha124/frontend'
            }
          }
        stage('Remove old images') {
            steps {
                sh 'docker rmi -f harsha124/frontend'
              }
          }
        stage('Docker run'){
            steps{
                sh 'docker container run -dt --name web -p 80:80 harsha124/frontend'
            }
         }
	}
}
